### ISSUE TITLE
cannot import wordcloud

### ISSUE THREAD

**Issue by Sarangam** [amueller/word_cloud#147]
hi, i am unable to import wordcloud on a server where i am running a script on a flipside i am able to run it locally.

Traceback (most recent call last):
  File "wc.py", line 7, in <module>
    from wordcloud import WordCloud

**Comment by amueller** [comment]
how did you install it?

**Comment by Sarangam** [comment]
sudo pip install wordcloud then i tried apt-get and pip3 also..the packages are installing,but i find problem in importing

should i be careful about the path it installs?

**Comment by Sarangam** [comment]
when i tried installing wordcloud locally i had a warning about microsoft visual studio c++,then i installed microsoft compiler.should i install microsoft visual on server too?

**Comment by amueller** [comment]
if you don't get an when installing, you don't need to install anything else on the server. The problem is probably that you installed wordcloud in a different python environment than the interpreter you are running.
How are you executing the python file?
what does ``which python`` and ``which pip`` give you?
Is the path you installed wordcloud to in ``sys.path`` when you run python?

**Comment by Sarangam** [comment]
Hi, the error got fixed it is because of the python script file which i had saved as "wordcloud.py" itself,i had to rename it to run the wordcloud package

**Comment by Sarangam** [comment]
Hi, is there a way i can save wordcloud  as a png file on server?

**Comment by amueller** [comment]
http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud
to_file
