### ISSUE TITLE
Is there a way to make coloring stable?

### ISSUE THREAD

**Issue by sakvaua** [amueller/word_cloud#212]
What's the best way to make wordcloud use the same set of colors for different wordclouds? I want to do a sort of moving time window wordcloud animation and want to have consistent colors between frames.
Thanks!

**Comment by amueller** [comment]
You can provide your own color function to do that. If you want the same word to have the same color each time, you can provide a color function that only depends on the word, for example.

**Comment by sakvaua** [comment]
Thanks, Andreas. 
I'm not quite sure hot to make color depend on the word rank. The coloring function receives (word, font_size, position, orientation, random_state=None, **kwargs) but not rank. I assume I can use font size as a proxy of rank but not sure that's the best strategy given I don't have a list of all possible font sizes.

**Comment by amueller** [comment]
ah, you want it to depend on rank... I'm surprised that's not deterministic already. The function should be called in order of the rank, and exactly once per word. Did you fix the random state?

**Comment by sakvaua** [comment]
Now I feel stupid... I used random.seed to seed the random number generator instead of using random_state=xxx. Thanks again!

**Comment by amueller** [comment]
glad you got it worked out :)

**Comment by abubelinha** [comment]
I am not sure if I understand the `random_state` parameter of [`wordcloud.WordCloud()`](https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html) (I think it is not explained).

Is it supposed to be a random seed in order to fix the output?  
So for a given set of words, I can get a wordcloud with **random** but **repeatable** colors and positions, as far as I re-run my script passing always the same `random_state` value?

Thanks

**Comment by amueller** [comment]
it can be a seed or a numpy random state, and yes, your understanding is correct.
