### ISSUE TITLE
Word Color from Frequency

### ISSUE THREAD

**Issue by SL36** [amueller/word_cloud#256]
How can I create a custom color function that will color the words along a gradient, according to their frequency?

Currently I'm using generate_from_frequency to create a word cloud using a dictionary of 100 keys (Words) with values ranging from 5-35,000.  Works well to size words according to value, but color is random.

e.g. 100 words with corresponding frequencies - words with lowest frequencies are lightest, and highest frequencies are the darkest.  I already have a custom colormap, but this could be applied using a matplotlib colormap. 

The solution is alluded to in this issue: #212, but I can't figure out how to implement.  Any help is much appreciated.

**Comment by amueller** [comment]
You could write your own color function similar to this:
https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py#L88

but instead of picking the color randomly you could use the fontsize that is passed. For some reason I didn't pass the frequency to the color_func, but the fontsize should be a reasonable surrogate.
You need to map that to a float to use the color map, the easiest way I can come up with without thinking about it is just passing a max.

So something like
```python
class colormap_color_func(object):
    """Color func created from matplotlib colormap.
    Parameters
    ----------
    colormap : string or matplotlib colormap
        Colormap to sample from
    Example
    -------
    >>> WordCloud(color_func=colormap_color_func("magma"))
    """
    def __init__(self, colormap, max_font_size):
        import matplotlib.pyplot as plt
        self.colormap = plt.cm.get_cmap(colormap)
        self.max_font_size = max_font_size

    def __call__(self, word, font_size, position, orientation,
                 random_state=None, **kwargs):
        if random_state is None:
            random_state = Random()
        r, g, b, _ = 255 * np.array(self.colormap(font_size / self.max_font_size))
return "rgb({:.0f}, {:.0f}, {:.0f})".format(r, g, b)
```

**Comment by SL36** [comment]
Thanks, I will work with this
