### ISSUE TITLE
Dynamic stopwords list

### ISSUE THREAD

**Issue by jjduhamel** [amueller/word_cloud#29]
Hi, I've been using this tool for a while to generate word clouds from irc logs and it's working great.  Thanks!  Recently, someone started spamming one of the channels I'm following with profanity, which caused the home page of my website to in turn display profanity.  I was able to resolve the issue by appending a list of profane words to stopwords and rerunning setup.py.  However, I'd prefer to be able to place text files in a folder somewhere and for those to automatically be blocked.  I'd recommend /usr/local/share/stopwords.  Would you be open to adding this?  I could help with the development.

**Comment by ArminMne** [comment]
Hi amueller,
I have problem with stopwords. I have made my own list of words in txt file but still some words appears on word cloud even if they are in my txt file.
First step I made copy of original stopwords
`remove= STOPWORDS.copy()`
Then import file
`bosnianstopwords = open('C:/Users/aalibasic/PycharmProjects/TwitterTimelineWordCloud/bosnianstopwords.txt', 'r', encoding='UTF-8')`
Then using for loop add these words on dictionary remove, at the end I use [:-1] so that \n will not appear with word. I checked it and it is ok after that all words are just fine and in a form of dictionary like original STOPWORDS.
```
for rijec in bosnianstopwords:
    remove.add(rijec[:-1])
```
Then just use parametar at the end when calling word cloud
`stopwords=ukloniti,`

But some words still appear. How is that possible?

**Comment by amueller** [comment]
what is ``remove`` and what is in ``wordcloud.words_`` after you built the wordcloud?

**Comment by ArminMne** [comment]
Remove is just a dictionary where I added new words that I want to remove from showing in wordcloud. At the end, I have these words appearing in wordcloud.words_

**Comment by amueller** [comment]
Well, can you provide the exact lists or code to reproduce? It might be a capitalization issue.
Make sure all your stopwords are lowercased. They are compared to the lowercased version of the words. I fixed this here: #129

**Comment by ArminMne** [comment]
YES. That was the problem! Now everything is ok. Sorry for wasting your time Andreas and thank you very much for this nice library!

**Comment by amueller** [comment]
na, you pointed out a flaw in the design. This is not documented and very unexpected behavior, so I fixed it ;)
