### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by typ431127** [amueller/word_cloud#304]
File "/usr/local/python3/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

Centos7
python3.6.1

**Comment by amueller** [comment]
It would be helpful if you gave the full traceback. I imagine this happens when importing matplotlib. a) matplotlib is not required for running wordcloud. b) your matplotlib is configured to use the tk backend, but you don't have tk installed. Choose a [different backend](https://matplotlib.org/faq/usage_faq.html#what-is-a-backend), for example by ``agg``

**Comment by typ431127** [comment]
Thank you, I am using python2 for the time being

**Comment by amueller** [comment]
that is completely unrelated....

**Comment by typ431127** [comment]
老铁，python3真的不可以哦

**Comment by amueller** [comment]
![image](https://user-images.githubusercontent.com/449558/31674208-3ada0646-b32f-11e7-853b-021407d6d716.png)
