### ISSUE TITLE
Problems with lemmatisation (I assume)

### ISSUE THREAD

**Issue by val-st** [amueller/word_cloud#511]
Hi, thanks for this awesome package! 

It works well, but I'm having a problem with one word: my dataset contains the word 'santos' quite often (as in, lower case version of the former Colombian president). However, the word cloud displays it as 'santo'. I assume that it is lemmatising the words, and that the lemmatisation is wrong (I had that problem with lemmatisation before). Could this be the case, and if yes, how could I fix this? I don't need to do any lemmatisation on my dataset as it already contains only lemmatised words.

Thanks for your advice!

**Comment by amueller** [comment]
Thanks for the report. I think right now it tries to be "smart" and do basic stemming if a word is present with an "s" and without an "s" at the end.
So this means "santo" is also in the dataset (which might be legitimately a different word). You can turn off this behavior by passing ``normalize_plurals=False``.

You can skip all the preprocessing if you use ``generate_from_frequencies`` instead of ``generate`` and pass a dictionary of word frequencies.

**Comment by val-st** [comment]
Thank you very much for your prompt answer, I turned off the normalisation and it worked perfectly. Thanks!
