### ISSUE TITLE
Unclear if including stopwords in bigrams is good

### ISSUE THREAD

**Issue by amueller** [amueller/word_cloud#557]
I'm not sure if the solution of #528 is good in all cases.
It might add "the" to many nouns for example. I think it's a bit tricky to decide whether option 1) or 2) are better. I'm a bit afraid of adding another option, but I'm not sure how else to solve this.

cc @carlgieringer

**Comment by wjharbin** [comment]
I consider this option feature would be necessary, maybe with 3 choices (1) single word like before, I think this should be the default, Oftentimes the goal is just to make 'count' on any single word except the stopwords. (2) current version (with consideration of collocations), and (3) collocations only (maybe an interesting thing to have). Thanks.

**Comment by amueller** [comment]
Sorry, I'm not sure I follow what options you are suggesting. Before it removed the stopwords before computing collocations, which was a bit weird.
You can turn of collocations by setting colocations=False if you only want to look at single words.

**Comment by wjharbin** [comment]
My bad I did not realize that collocations can be turned off. Well, I disagree with your 'a bit weird' comment on the old settings... For (3) I was just suggesting maybe to make a CollocationCloud.

**Comment by amueller** [comment]
So you think the old setting was good, even though it showed collocations that didn't appear in the  text?

**Comment by wjharbin** [comment]
my thought is if the goal is simple (count the words other than stopwords), then should do it plain and simple. And the result is straightforward and clear. Feeling with collocations, the result might not be that clear. The case you mentioned "showed collocations that didn't appear in the text" should be fairly rare?

**Comment by amueller** [comment]
Yes indeed, the situation is more complicated and the source of the issue you observed. I'm not sure how rare it is to observe collocations that are not in the text. If there are common phrases in the text that are more than two words long and contain stop words then this happens, so "United States of America" might produce "States America".

**Comment by amueller** [comment]
Can you check if current master has this fixed the way you expected?

**Comment by wjharbin** [comment]
Enlighten me on how to test it... is there a new version of WordCloud package? It definitely sounds right to not include the stop words in bigrams.

**Comment by amueller** [comment]
I haven't released a new version yet, but you can install the development version from github. Though if you haven't installed a development version before that might be tricky as it requires a compiler.
The command would be
```
pip install git+https://github.com/amueller/word_cloud.git#egg=wordcloud
```

**Comment by wjharbin** [comment]
never done the development version before. most likely I didnt do it right -  I ran that command and then rerun the code. the result seemed the same. 'said' still shows up as it is in the stopwords.

**Comment by freeIsa** [comment]
Hi,
I was pondering on the stopwords + collocation question. Allowing stopwords to be part of collocations - especially since the code is only considering bigrams - is, in my opinion, tricky. E.g. if my text has several occurrences of _"point of view"_, my wordcloud will contain both _"point of"_ and _"of view"_. 
In my opinion, discarding stopwords at the very beginning and therefore getting "point view" in the wordcloud would be more informative. One way to go could be having a flag letting the user decide whether they want stopwords in collocations (if they don't, stopwords can be discarded before creating unigrams & bigrams).

I was also wondering whether tokenization could be expanded to consider collocations longer than 2 (with a user-specified max length, perhaps up to 4/5 words), in which case having stopwords in them would make much more sense. That would allow for _"point of view"_ and _"United States of America"_ to be considered and shown as unique entities.

**Comment by carlgieringer** [comment]
Yeah, understandable.  General consensus may not be possible.  I think having options for different behavior may make sense.  From my perspective, I still am thinking of the example I gave in #528 where "thank you very much" became the 'collocation' "thank much".

**Comment by amueller** [comment]
yeah, so the way I modified your patch that still doesn't happen any more. I might just do a release with the way it is now and see what people say.
